### ISSUE TITLE
Bump schema version to 1.0 before initial release

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Plaster#114]
Need to update the schema file and Plaster.psm1 line:

``` powershell
$LatestSupportedSchemaVersion = [System.Version]'0.4'
```

to 1.0.

**Comment by rkeithhill** [comment]
And while we are at it, bump the PSD1 version to `1.0.0`.

**Comment by daviwil** [comment]
Cool!  I was wondering if we were going to announce it as 1.0 :)

**Comment by rkeithhill** [comment]
Actually I'm open to what version we chose.  I just didn't want to chose by virtue of whatever happened to be in the PSD1/scheme files when we push out this release in October.  :-)

**Comment by daviwil** [comment]
I'd say we can declare 1.0 when we feel the schema is stable. If it's "almost there"  we could call it 1.0-alpha.1,

**Comment by rkeithhill** [comment]
I wish we could use semver in the Module manifest.  Last I checked it had to conform to System.Version.  

Likewise, the schema version number is currently restricted to Major.Minor.  There really isn't an "implementation" where there could be bugs (I don't think) so I didn't bother with a patch version.  

WRT to stability, I think we can get by with "additions" only which means we only bump the schema's minor version number.  An old Plaster module install might notify the user it can't process a particular template unless the user updates to the latest Plaster module.  

In theory, Plaster could process older templates that have a different major version number.  Plaster would have to take into account the schema breaking change difference and validate against the schema for that version.  This is why Schemas is folder - anticipating there may be multiple schema files for v1, v2, etc.

**Comment by daviwil** [comment]
Ahhh right, yeah, can't use semver.  If we only have additions going forward then we'll be fine with 1.0.  I'm not even that concerned about having a 2.0 within 6 months if some important breaking schema changes are needed.

I like the idea about being able to let the user known they need a newer version of Plaster if the schema version of the template is too new.  I'll have to keep this in mind so that we can tell people to mark their Plaster template modules as having a minimum version of 1.0 without a max version requirement unless absolutely needed.

**Comment by daviwil** [comment]
Closing this since you bumped the version last night.
