### ISSUE TITLE
Consider ripping out support for compressed template pkgs

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/Plaster#116]
As we are leaning towards using PowerShell modules as a package mechanism and PowerShell Gallery for distribution, I don't think there is a need anymore for Invoke-Plaster to be able to operate on a zip file e.g. `Invoke-Plaster -TemplatePath .\newModuleTemplate.zip`.  Distribution via PowerShell Gallery means that by the time the module containing the template(s) hits the local machine, it is already unzipped.

@daviwil  is there a "todo" or "task" label we can use for issues like this?

**Comment by daviwil** [comment]
I kinda like the zip support, but I suppose you're right, users are less likely to use use zipped templates. Also, no archive cmdlets on PSv3 and PSv4, so that's a downside. 

Regarding the task/todo label, feel free to create one. I'd say using 'enhancement' is also fine even if not totally indicative of the intent.

**Comment by rkeithhill** [comment]
Fixed by PR #132
