### ISSUE TITLE
Set up platyPS for cmdlet documentation

### ISSUE THREAD

**Issue by daviwil** [PowerShell/Plaster#133]
Seems like this might be a good time to get our overall cmdlet documentation strategy going.  I'll see if I can get platyPS set up so we can write our cmdlet docs in Markdown.

**Comment by rkeithhill** [comment]
I wonder if this is something we can/should work into the build.psake.ps1 for the New Module template?

**Comment by daviwil** [comment]
I was thinking the same! Maybe a "Docs" task would be nice to have?

**Comment by rkeithhill** [comment]
As Teal'c would say - "Indeed".

**Comment by davegreen** [comment]
I've made an initial attempt at this in the psake script. I'd very much like some feedback on how you'd like both the generation/update for the markdown, as well as the generation of the external help when installing or publishing a module.

At the moment, my thoughts are probably to split those two stages, so that creating the external help is tried whenever doing an install or a publish, but does not depend on generating the markdown, which can be called explicitly, or created manually. This approach isn't really evident in the pull request at the moment, as the external documentation generation depends on creating the markdown.

**Comment by rkeithhill** [comment]
This was address by PR #136
