### ISSUE TITLE
A generated module manifest contains two identicals GUID

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#169]
```Powershell
#
# Module manifest for module 'moduleManifest-67578f84-aaeb-491b-8bb2-25acd5888678'
#
# Generated by: LaurentDardenne
#
# Generated on: 20/10/2016
#

@{
...
# ID used to uniquely identify this module
GUID = '7cd7d08e-4560-479c-92f5-ae9937d9408b'
...
```
Is-it correct ?

**Comment by rkeithhill** [comment]
I'm not following you, where are the two identical GUIDs?  If you are referring to the fact that this guid `67578f84-aaeb-491b-8bb2-25acd5888678` is different from this one `'7cd7d08e-4560-479c-92f5-ae9937d9408b`, that is correct.  The first one was generated to form a temporary filename. We generate to a temp file so that we can then compare against the original PSD1 to see if there are any conflicts.  However, I can see that the auto-generated comment containing the value passed to the Path parameter should not reflect the temp filename but the permanent filename.  I'll try to get that changed tonight.

**Comment by LaurentDardenne** [comment]
_I'm not following you, where are the two identical GUIDs?_
Yes,  I was wrong : two different guid

_that is correct_
Ok.

_I I'll try to get that changed tonight_
Thanks :-)
