### ISSUE TITLE
Add support for UTF8-noBOM encoding

### ISSUE THREAD

**Issue by gaelcolas** [PowerShell/Plaster#20]
Hi,
The Set-Content in PowerShell use UTF-8 _with_ BOM, which fails when consumed in tools such as Test-Kitchen (might be a ruby thing?).
Could you add support in Plaster for an encoding UTF8-NOBOM?

I found this workaround:
```powershell
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding($False)
[System.IO.File]::WriteAllLine($filePath, $PLASTER_FileContent, $Utf8NoBomEncoding)
```
Thanks,
Gael

**Comment by rkeithhill** [comment]
I'm not a huge fan of using UTF8 without a BOM as it can also cause [problems with editors](https://blogs.msdn.microsoft.com/oldnewthing/20070417-00/?p=27223/).  I guess using encoding ASCII is not satisfactory?  

I was hoping to just ride the coat tails of the encodings that PowerShell normally supports.  Oh well, I suspose you won't be the only one to ask for this.  I'll look into it.  

BTW you would want to use `WriteAllText` instead of `WriteAllLines` since the file content is represented as a single string (easier to regex replace with a single string).

**Comment by vors** [comment]
I recently did the same exercise for [platyPS](https://github.com/PowerShell/platyPS). PowerShell standart class for encodings is `Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding`. That's what `Set-Content` and others use. It allows you cast strings to encodings and so on. Unfortunately, it doesn't provide flexibility for BOM / no-BOM. For me, no-BOM was crucial, because github cannot handle BOM correctly. So I settled on using  `System.Text.Encoding` class for [encoding parameters](https://github.com/PowerShell/platyPS/blob/master/docs/New-MarkdownHelp.md#-encoding).

**Comment by rkeithhill** [comment]
@vors I've seen problems with GitHub and Unicode.  What's the issue with GitHub and UTF8 w/BOM?

**Comment by vors** [comment]
In markdown, somebody can put a "yaml metadata header" on top of document:

```yaml
---
schema: 2.0.0
---
...
```

And it would be rendered like [a table](https://github.com/PowerShell/platyPS/blob/master/Examples/PSReadLine.v2/Get-PSReadlineKeyHandler.md)

This first `---` has to be the first symbol in the file.
If there is BOM, github start treating `---` as a part of header and it all renders pretty ugly.

**Comment by rkeithhill** [comment]
Good to know.  Thanks.

**Comment by MartinSGill** [comment]
I'm also in favour of disallowing the BOM. I've also encountered issues in git, but also in some editors. web UI's to browse repositories and various command line text tools.

So much so that it's become a coding standards requirement for my team that all production powershell scripts and generated files are not allowed to use BOMs. So this becomes a requirement for me.

**Comment by rkeithhill** [comment]
The manifest schema allows you to set `UTF8-NoBOM` but I need to implement the functionality to do that.  I'll get that in tonight.
