### ISSUE TITLE
Improvement Request - CI/CD choice for Projects

### ISSUE THREAD

**Issue by JayPowerUser** [PowerShell/Plaster#247]
I know that this can be added manually by editing the XML file, but adding an option for CI/CD implementation would be a nice addition. Appveyor, Jenkins ,etc... Having the parameter store the secure ENV Variable for these would be an added benefit.

**Comment by rkeithhill** [comment]
The intent with Plaster is not to have a single template but multiple templates to address multiple scenarios. Some folks just want to build a module for personal use and others want to host on GH, build it and publish to the PowerShell Gallery.  We pull the build pipeline we had in the earlier versions of Plaster because we decided that builds shouldn't be part of Plaster (a templating engine for PowerShell).  We are spinning up a separate project the builds and that will eventually provide a Plaster template to configure a project to perform builds.  If you look in the Examples folder you can see some of the early work we did on this that will be migrated to either PlasterBuild and/or psake.

**Comment by rkeithhill** [comment]
BTW we had a mechanism for storing secrets in DPAPI.  That works great locally but not for remote builds like via AppVeyor/Travis.

**Comment by JayPowerUser** [comment]
Thanks for the quick response and explanation.
