### ISSUE TITLE
XML Configuration in a PowerShell Tool?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/Plaster#30]
Why does this have XML configuration? What is this, the 1990s? 😉

**Comment by rkeithhill** [comment]
Well, because we can have comments in the templates.  I can add large sections of "replacement" text in a `modify` directive using a CDATA section and the schema was easy for me write.  :-)  Oh, and PowerShell handles XML very nicely.  Ooh, and I don't have to escape `\` in strings.  Of course, you do have to sometimes use an entity reference e.g. `&amp;` or `&quot;`.  :-)  Hey, no format is perfect.

All that said, this was a question posed earlier (which format to use) and we've moved past that design decision.  The manifest format is XML.  I just finished writing the XML schema for the manifest format on Sunday.  Which works nicely when authoring in Visual Studio.  I just wish VS Code was schema aware. And if it is, I haven't figured out how to enable it.

**Comment by Jaykul** [comment]
Uhm. You're rejecting json. I have no problem with that. How about psd1? It doesn't have any of those problems ;-P

**Comment by rkeithhill** [comment]
I looked into and prototyped a PSD1 but it was starting to get ugly and I hadn't even specified that much it.  Have a looksee -  https://github.com/PowerShell/Plaster/blob/master/Examples/NewModuleTemplate/plasterManifest.psd1

**Comment by Jaykul** [comment]
You could make it look like DSC configurations, if you wanted to.  

Of course, if I were doing it in psd1, I would write a couple of functions and white-list them when reading your metadata. You could do something like this, using custom functions with my Configuration module (and it would be round-trip-able):

```posh
@{
    Metadata = Metadata 'New Module Project' -Version '0.1.0' -Tags @('Module', 'Project')
    Parameters = @(
        Parameter 'ModuleName' -Type 'string' -Required
        Parameter 'ModuleVersion' -Type 'string' -Required
    )
    Content = @(
        Content -Type 'File' -Source '_gitignore' -Destination '.gitignore'
        Content -Type 'File' -Source 'Module.psd1'' -Destination '$($Parameters.ModuleName).psd1'
        Content -Type 'File' -Source 'Moodule.psm1' -Destination '$($Parameters.ModuleName).psm1'
    )
}
```

Actually, looking at that (and depending on what else there is), you wouldn't necessarily need the hashtable, you could separate things by their types, later:

```posh
@(
    Metadata -Name 'New Module Project' -Version '0.1.0' -Tags @('Module', 'Project')

    Parameter 'ModuleName' -Type 'string' -Required
    Parameter 'ModuleVersion' -Type 'string' -Required

    Content -Type 'File' -Source '_gitignore' -Destination '.gitignore'
    Content -Type 'File' -Source 'Module.psd1' -Destination '$($Parameters.ModuleName).psd1'
    Content -Type 'File' -Source 'Moodule.psm1' -Destination '$($Parameters.ModuleName).psm1'
)
```

**Comment by wiltaylor** [comment]
I like the PSD1 file over xml personally. You also add a lot of extra flexability using PSD1 files. Kinda the whole reason you would use a tool like this over say yo.

**Comment by rkeithhill** [comment]
Such as schema-driven validation and schema-driven Intellisense in an IDE?  Oh wait, I'm talking about XML.  ;-)  Seriously though, I've finished the XSD and have integrated it into `Invoke-Plaster` and `Test-PlasterManifest`.  Should be checking that in in the next few days after fixing a few Pester tests.

**Comment by wiltaylor** [comment]
I think you are misunderstanding the reason we are suggesting psd1 files over xml. It is not just the formating and intellisense. Psd1 files are code files as well as configuration files, meaning you get dynamic configuration for free, you can just chuck in powershell code. Xml files will require you to write a tokenisation system to do that and/or some system to execute scripts from it indirectly. If you look at build systems you will see a trend towards configuration files being code rather than static xml or json files.

End of the day though it is your call. Looking forward to your checkin so we can have a play with it :).

**Comment by kilasuit** [comment]
+1 for moving to PSD1 configuration files as I think this would be easier for maintainability for our own templates going forward.

**Comment by rkeithhill** [comment]
@kilasuit Not going to happen for the initial version.  I just submitted the PR for XML schema validation and have plenty left to do for a targeted 1.0 release in mid-August.  

In reference to the original question of this post "XML Configuration in a PowerShell Tool", I will point out that both format and type data are specified as XML.
