### ISSUE TITLE
Validation of a 'parameter' node

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#42]
All 'parameter' nodes with "type='input'" are [string] type : 
I can declare this :
```Powershell
cd 'C:\Users\Laurent\Downloads\Plaster-master\Examples\NewModuleTemplate'
Import-Module ..\..\Plaster.psd1

$PlasterParams = @{
    TemplatePath = $PWD
    Destination = '..\Out'
    ModuleName = ''
    FullName = 'John Q. Doe'
    Version = '-1'
    Options = 'PSake','Pester','Git','None'
    Editor = 'VSCode'
    License = 'MIT'               
}

Invoke-Plaster @PlasterParams
```

- 'ModuleName' is a correct string, but not a valid filename.
- 'Version' is a valid string, but not a valid version.
- 'Options' is a valid set, but the values seems inconsistent.

How to control these cases ?
How to known the valid values for a 'Powershell Gallery' template ?

**Comment by MartinSGill** [comment]
This [comment](https://github.com/PowerShell/Plaster/pull/52#issuecomment-234016198) by @rkeithhill suggests this might be about to change.

**Comment by rkeithhill** [comment]
@MartinSGill After thinking about this some more, I think that not only do I want to change the `type` value from `input` to `text` but I'm also tempted to add a subtype attribute (looking for better name) e.g. 
```xml
<parameter name="FullName" type="text" subtype="fullname" .../>
<parameter name="Email" type="text" subtype="email" .../>
```
This would allow the "text" type to share more code (instead of the current duplication).  The only thing I don't like is I don't know how in XML schema to disallow the subtype attribute when the value of the type attribute is not "text".  It might have to be a manual validation check.

That said, this would allow for subtypes like: `filename`, `path`, `version` where we could validate the user's input.

**Comment by MartinSGill** [comment]
Maybe `type` and `content` or `purpose` as names? Just suggesting stuff, `subtype` would work for me.

**Comment by rkeithhill** [comment]
Maybe not `content` since there is a separate `content` section but keep the suggestions coming.

**Comment by LaurentDardenne** [comment]
I thought to the dynamic parameters Powershell.
The error may occur later in the tempalte processing, how to undo an erroneous installation ?

**Comment by rkeithhill** [comment]
The checks (if any - not sure `author` or  `fullname` needs validating) will happen in Test-PlasterManifest.  That failure will not allow the template processing to continue.  It will also result in no dynamic parameters being defined.
