### ISSUE TITLE
Remarks around the localization of the ' PlasterRessources.psd1' file 

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#55]
I am localizing the PlasterRessources.psd1 file and I have some remarks about it.
 
**PlasterResources.psd1** 
The key 'ManifestNotValid_F1'   is for a valid  Xml file.
the key 'ManifestNotValidXml_F1' is for a not well-formed Xml file.   

Key 'UnrecognizedAttribute_F2' -> Unrecognized manifest attribute {0} on element {1}.
Unrecognized manifest attribute is managed by the XSD.
May be rename it to 'UnrecognizedContentTypeAttribute_F2'

Likewise for 'UnrecognizedParameterType_F2' -> Unrecognized parameter type '{0}' on parameter name '{1}'.

The key 'UnrecognizedContentElement_F1','UnrecognizedParametersElement_F1' are managed by the XSD ?
May be rename it to 'NotImplementedElement' ?

**InvokePlaster.ps1**
I know is temporary, but 'Create' is not localized :  
```Powershell  
  # TODO: Temporary - remove this when this function makes use of ProcessFile
  WriteOperationStatus 'Create' (ConvertToDestinationRelativePath $dstPath)
```

**TestPlasterManifest.ps1**
Is it possible to save the original exception ?
```Powershell
   Write-Error ($LocalizedData.ManifestNotValidXml_F1 -f $Path)
 
   #Something like this
   $Ex= (new-object System.ApplicationException(($LocalizedData.ManifestNotValidXml_F1 -f $Path),$_.Exception))
   $Er=New-Object System.Management.Automation.ErrorRecord(
         $Ex, 
         "InvalidFormat", 
         "InvalidData",
         ("[{0}]" -f $Path)
       )             
   Write-Error -ErrorRecord $Er
```
  
**PlasterManifest-v1.xsd**
The following element is not yet documented (<xs:documentation>) : 
```xml
 <xs:attribute name="store" type="ptd:StoreFormatType"/>
```

The following xml is valid for Test-PlasterManifest
```xml
<?xml version="1.0" encoding="utf-8"?>
<plasterManifest>
  <metadata>
    <id>string</id>
    <version>string</version>
    <description>string</description>
    <tags>string</tags>
  </metadata>
  <content/>
</plasterManifest>
```
Invoke-Plaster does nothing :-)
```Powershell
$PlasterParams = @{
    TemplatePath = "$PWD"
    DestinationPath='..\out'
}
Invoke-Plaster @PlasterParams
```

**Comment by rkeithhill** [comment]
> The key 'ManifestNotValid_F1' is for an **in**valid Xml file.
 the key 'ManifestNotValidXml_F1' is for a not well-formed Xml file. 

The first is for an invalid manifest file.  That could be because the XML is not well-formed or the manifest violates the schema.  The second is for a not well-formed XML file.   If you want to tweak the wording (English as well), go for it.

> 'UnrecognizedAttribute_F2' 

This string could probably go away as the schema does validate the values of the type attribute.  Looks like I missed this one when integrating the schema.  But I'm having a hard time removing the `default` case from these.  I think we should replace the one place that uses `UnrecognizedAttribute_F2` with `UnrecognizedParameterType_F2`.  That is the right message for the one spot using UnrecognizedAttribute_F2.  Let's leave `UnrecognizedParametersElement_F1` as is. It is very unlikely to get called but the `default` backstop is there just in case.

> Create not localized.  

It is in the string table. Looks like I missed a place where I should be using $LocalizedData.OpCreate

> Is it possible to save the original exception ?

Possibly but I wouldn't use ApplicationException. Use of that exception fell out of favor a long time ago.  :-)  

> The following element is not yet documented (xs:documentation) : 

Yup, I can add that.

> The following xml is valid for Test-PlasterManifest, Invoke-Plaster does nothing

Well it was even worse when it thought `<foo></foo>` was a valid manifest. The thing about schema is if the doc element (with the correct target namespace) isn't recognized then the schema validator says this is not a document I validate.  I have added manual check for the correct doc/root element. Looks like I need to add a manual check that the doc element has the correct target namespace.

**Comment by rkeithhill** [comment]
> <xs:attribute name="store" type="ptd:StoreFormatType"/>

The attribute is documented where it is declared - see [line 67](https://github.com/PowerShell/Plaster/blob/master/Schema/PlasterManifest-v1.xsd#L67).
