### ISSUE TITLE
-Force should indicate when it overwrites a file

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#79]
Into this file "Plaster/examples/README.md" it is say : 
_"If you run the Invoke-Plaster command a second time, you see Plaster's file conflict handling. 
You can use the -Force parameter to automatically overwrite existing files."_

But today the _-Force_ parameter displaying 'Conflict' state and not 'Create' state.

And the use of the 'newModuleManifest' element should not displayed 'Conflict' but 'Create'( or 'Overwrite' ?) :
![conflict-newmodulemanifest](https://cloud.githubusercontent.com/assets/4894452/17302630/678c5cb6-581d-11e6-9bbb-e0dfeaa14eca.png)

Moreover, after the call to Invoke-Plaster, one can not know what it is happened.

**Comment by rkeithhill** [comment]
`-Force` won't suppress the display of `Conflict`.  `Conflict` tells you that file (copied, expanded template or modified) is different than the file that already exists at the destination.  What the `-Force` parameter does do is prevent Plaster from prompting you with how you want to handle the conflict by always overwriting the file at the destination. 

That said, I can see where this can be a bit confusing.  If you don't use `-Force` you see this:
```
 Conflict with existing file FooUtils.psd1

Plaster file conflict
Overwrite C:\Users\Keith\GitHub\PowerShell\Plaster\examples\Out\FooUtils.psd1
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
Identical to existing file FooUtils.psm1
```
We don't output anything in the "Y" case to indicate that we did indeed overwrite the file.  Perhaps we need an `Overwrite` operation as you suggest.   And in the case of `-Force` we would display that after the `Conflict` message (or perhaps in place of it).

Regarding the newModuleManifest, I believe you see that because the New-ModuleManifest command generates a unique guid every time.

Could you re-title this issue something like "-Force should indicate when it overwrites a file"?

**Comment by LaurentDardenne** [comment]
_Perhaps we need an Overwrite operation as you suggest. 
And in the case of -Force we would display that after the Conflict message (or perhaps in place of it)._
Yes, today the color Red suggests that there is an error on the file.
For me, there is a contradiction between what the function does and what he displays.
