### ISSUE TITLE
Provide a way to store common parameter values for templates

### ISSUE THREAD

**Issue by randomchance** [PowerShell/Plaster#9]
Reading through the project and I stumbled on this:

>After having run the Invoke-Plaster command for a few days, I'mm already pining for a Yeoman like store feature where I can add parameter attribute to say that the parameter can be stored and then its value recalled as the default value. So after I've entered my name or copyright notice once, it can be stored and used as the default value instead of the template provided default value.

I was just wondering if there you could leverage the built in powershell default parameters for this?

**Comment by daviwil** [comment]
Certainly possible.  Not sure if Keith has a different plan for that

**Comment by rkeithhill** [comment]
I'm not sure that would be flexible enough besides, to persist the $PSDefaultParameterValues you'd need to poke into the user's profile or something like that.  

What I was thinking is that we'd have a per-user app data dir that had something like `<unique-template-id>.json` (or xml) and that for every parameter the template author marked as `store` we would squirrel away the user's response when they enter a value (as opposed to selecting the default).  The next time they run the template we would look for that file, open it if it exists and for parameters marked `store` retrieve the default value from the file rather than the template manifest.

**Comment by gaelcolas** [comment]
The store with encrypt function is definitively something I'd like!
I drafted a helper function to do that here: https://github.com/gaelcolas/lib.common/blob/master/ProtectedFileHelpers.ps1
It allows to either encrypt with DPAPI per user/machine, or specify credentials to generate a key based on the tuple.

**Comment by rkeithhill** [comment]
@gaelcolas Yup, we've got similar functions in our build.ps1 file to support encrypt/decrypt of the PSGallery api key.

**Comment by gaelcolas** [comment]
Adding support for key based encryption would be nice tho, so that you can move that file around, instead of generating a new one on different computer. 
Doing so, you separate the credential management (to encrypt/decrypt the 'profile') from the profile file itself.
Useful when you have several Jenkins slave for instance.

**Comment by randomchance** [comment]
My gut reaction is that if you support encrypted secrets you should have them per user (at least to start with).

1. it doesn't preclude having importable "team" defaults, with the separate considerations that would require.
1. It's conceptually simpler.
2. It defaults to a more secure model
3. It prevents the personal default option being hacked into a team default option, and then scope creeping it's way to *(insert environment specific use case here)*. 
4. You don't accidentally have "personal" secrets accessible to team members.

And speaking of scope creep ..
A plugable configuration provider would be pretty sweet - I'd like my build server to pull config from consul and api keys from vault (or some other web service). 

:D

**Comment by rkeithhill** [comment]
Also keep in mind the purpose of the file is just to supply customized default values to the user when they scaffold a new item (file, files, module project, DSC resource).  Not sure copying this file to another machine would be common.

BTW I've been thinking that maybe just a part of the file is encrypted.  Many default values e.g. `FullName, Options, Editor` don't need to be encrypted.  It would be nice to be able to see those contents in the file.  Those values that need to be encrypted can be encrypted and base64-encoded to store in the file as text.  Perhaps the store attribute value in the manifest changes from `true/false` to `text/encrypt`.

**Comment by rkeithhill** [comment]
I think we have a decent system for storing both plain text and encrypted `default values` per template.  I'm going to close this for now but after playing with the latest bits, you think it needs re-opening then let me know.  Or open a new issue.
